//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalAPILib.XifinAccessionSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xifin.com/schema/accessionSearch", ConfigurationName="XifinAccessionSearchService.accessionSearch")]
    public interface accessionSearch {
        
        // CODEGEN: Generating message contract since the operation AccessionSearch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1 AccessionSearch(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1> AccessionSearchAsync(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageHeader messageHeaderField;
        
        private AccessionSearchRequestPayload payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.xifin.com/schema/msgHeader", Order=0)]
        public MessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccessionSearchRequestPayload Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/msgHeader")]
    public partial class MessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organizationNameField;
        
        private string sequenceNumberField;
        
        private string userIdField;
        
        private string sourceApplicationField;
        
        private string orgAliasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
                this.RaisePropertyChanged("OrganizationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
                this.RaisePropertyChanged("SequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SourceApplication {
            get {
                return this.sourceApplicationField;
            }
            set {
                this.sourceApplicationField = value;
                this.RaisePropertyChanged("SourceApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OrgAlias {
            get {
                return this.orgAliasField;
            }
            set {
                this.orgAliasField = value;
                this.RaisePropertyChanged("OrgAlias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class SpecificPatientInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceTypeField;
        
        private string sourceIdField;
        
        private string sourceNameField;
        
        private string patientIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
                this.RaisePropertyChanged("SourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
                this.RaisePropertyChanged("SourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xifin.com/schema/types")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("StatusMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xifin.com/schema/types")]
    public partial class AddressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string regionField;
        
        private string zIPField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("AddressLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("AddressLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
                this.RaisePropertyChanged("ZIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xifin.com/schema/types")]
    public partial class NameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchRequestPayload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccessionSearchRequestMessage itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccessionSearchRequestMessage", Order=0)]
        public AccessionSearchRequestMessage Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchRequestMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessionIdField;
        
        private bool accessionWithAtleastOnePayorField;
        
        private string requisitionIdField;
        
        private string patientIdField;
        
        private string clientIdField;
        
        private string clientNameField;
        
        private NameType patientNameField;
        
        private string patientSSNField;
        
        private System.DateTime patientDOBField;
        
        private bool patientDOBFieldSpecified;
        
        private string payorIdField;
        
        private string payorNameField;
        
        private string subscriberIdField;
        
        private AddressType patientAddressField;
        
        private NameType insuredNameField;
        
        private int questionIdField;
        
        private bool questionIdFieldSpecified;
        
        private string questionResponseField;
        
        private System.DateTime dosFromField;
        
        private bool dosFromFieldSpecified;
        
        private System.DateTime dosToField;
        
        private bool dosToFieldSpecified;
        
        private bool displayPrimaryOnlyField;
        
        private bool sortByPatientLastNameField;
        
        private bool sortByPatientLastNameFieldSpecified;
        
        private string startRowNumberField;
        
        private string endRowNumberField;
        
        private string submissionIdField;
        
        private string clientPrimaryFacilityIdField;
        
        public AccessionSearchRequestMessage() {
            this.accessionWithAtleastOnePayorField = true;
            this.displayPrimaryOnlyField = true;
            this.startRowNumberField = "1";
            this.endRowNumberField = "100";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccessionId {
            get {
                return this.accessionIdField;
            }
            set {
                this.accessionIdField = value;
                this.RaisePropertyChanged("AccessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool AccessionWithAtleastOnePayor {
            get {
                return this.accessionWithAtleastOnePayorField;
            }
            set {
                this.accessionWithAtleastOnePayorField = value;
                this.RaisePropertyChanged("AccessionWithAtleastOnePayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequisitionId {
            get {
                return this.requisitionIdField;
            }
            set {
                this.requisitionIdField = value;
                this.RaisePropertyChanged("RequisitionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
                this.RaisePropertyChanged("ClientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public NameType PatientName {
            get {
                return this.patientNameField;
            }
            set {
                this.patientNameField = value;
                this.RaisePropertyChanged("PatientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PatientSSN {
            get {
                return this.patientSSNField;
            }
            set {
                this.patientSSNField = value;
                this.RaisePropertyChanged("PatientSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime PatientDOB {
            get {
                return this.patientDOBField;
            }
            set {
                this.patientDOBField = value;
                this.RaisePropertyChanged("PatientDOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientDOBSpecified {
            get {
                return this.patientDOBFieldSpecified;
            }
            set {
                this.patientDOBFieldSpecified = value;
                this.RaisePropertyChanged("PatientDOBSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PayorId {
            get {
                return this.payorIdField;
            }
            set {
                this.payorIdField = value;
                this.RaisePropertyChanged("PayorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PayorName {
            get {
                return this.payorNameField;
            }
            set {
                this.payorNameField = value;
                this.RaisePropertyChanged("PayorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public AddressType PatientAddress {
            get {
                return this.patientAddressField;
            }
            set {
                this.patientAddressField = value;
                this.RaisePropertyChanged("PatientAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public NameType InsuredName {
            get {
                return this.insuredNameField;
            }
            set {
                this.insuredNameField = value;
                this.RaisePropertyChanged("InsuredName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int QuestionId {
            get {
                return this.questionIdField;
            }
            set {
                this.questionIdField = value;
                this.RaisePropertyChanged("QuestionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuestionIdSpecified {
            get {
                return this.questionIdFieldSpecified;
            }
            set {
                this.questionIdFieldSpecified = value;
                this.RaisePropertyChanged("QuestionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string QuestionResponse {
            get {
                return this.questionResponseField;
            }
            set {
                this.questionResponseField = value;
                this.RaisePropertyChanged("QuestionResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime DosFrom {
            get {
                return this.dosFromField;
            }
            set {
                this.dosFromField = value;
                this.RaisePropertyChanged("DosFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DosFromSpecified {
            get {
                return this.dosFromFieldSpecified;
            }
            set {
                this.dosFromFieldSpecified = value;
                this.RaisePropertyChanged("DosFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime DosTo {
            get {
                return this.dosToField;
            }
            set {
                this.dosToField = value;
                this.RaisePropertyChanged("DosTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DosToSpecified {
            get {
                return this.dosToFieldSpecified;
            }
            set {
                this.dosToFieldSpecified = value;
                this.RaisePropertyChanged("DosToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool DisplayPrimaryOnly {
            get {
                return this.displayPrimaryOnlyField;
            }
            set {
                this.displayPrimaryOnlyField = value;
                this.RaisePropertyChanged("DisplayPrimaryOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool SortByPatientLastName {
            get {
                return this.sortByPatientLastNameField;
            }
            set {
                this.sortByPatientLastNameField = value;
                this.RaisePropertyChanged("SortByPatientLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortByPatientLastNameSpecified {
            get {
                return this.sortByPatientLastNameFieldSpecified;
            }
            set {
                this.sortByPatientLastNameFieldSpecified = value;
                this.RaisePropertyChanged("SortByPatientLastNameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=20)]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string StartRowNumber {
            get {
                return this.startRowNumberField;
            }
            set {
                this.startRowNumberField = value;
                this.RaisePropertyChanged("StartRowNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=21)]
        [System.ComponentModel.DefaultValueAttribute("100")]
        public string EndRowNumber {
            get {
                return this.endRowNumberField;
            }
            set {
                this.endRowNumberField = value;
                this.RaisePropertyChanged("EndRowNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SubmissionId {
            get {
                return this.submissionIdField;
            }
            set {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ClientPrimaryFacilityId {
            get {
                return this.clientPrimaryFacilityIdField;
            }
            set {
                this.clientPrimaryFacilityIdField = value;
                this.RaisePropertyChanged("ClientPrimaryFacilityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageHeader messageHeaderField;
        
        private AccessionSearchResponsePayload payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.xifin.com/schema/msgHeader", Order=0)]
        public MessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccessionSearchResponsePayload Payload {
            get {
                return this.payloadField;
            }
            set {
                this.payloadField = value;
                this.RaisePropertyChanged("Payload");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchResponsePayload : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusType statusField;
        
        private decimal totalPatientDueAmountField;
        
        private bool totalPatientDueAmountFieldSpecified;
        
        private decimal totalBalanceDueAmountField;
        
        private bool totalBalanceDueAmountFieldSpecified;
        
        private AccessionSearchResponseMessage[] accessionSearchResponseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal TotalPatientDueAmount {
            get {
                return this.totalPatientDueAmountField;
            }
            set {
                this.totalPatientDueAmountField = value;
                this.RaisePropertyChanged("TotalPatientDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPatientDueAmountSpecified {
            get {
                return this.totalPatientDueAmountFieldSpecified;
            }
            set {
                this.totalPatientDueAmountFieldSpecified = value;
                this.RaisePropertyChanged("TotalPatientDueAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalBalanceDueAmount {
            get {
                return this.totalBalanceDueAmountField;
            }
            set {
                this.totalBalanceDueAmountField = value;
                this.RaisePropertyChanged("TotalBalanceDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBalanceDueAmountSpecified {
            get {
                return this.totalBalanceDueAmountFieldSpecified;
            }
            set {
                this.totalBalanceDueAmountFieldSpecified = value;
                this.RaisePropertyChanged("TotalBalanceDueAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccessionSearchResponseMessage", Order=3)]
        public AccessionSearchResponseMessage[] AccessionSearchResponseMessage {
            get {
                return this.accessionSearchResponseMessageField;
            }
            set {
                this.accessionSearchResponseMessageField = value;
                this.RaisePropertyChanged("AccessionSearchResponseMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class AccessionSearchResponseMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int rowIdField;
        
        private NameType patientNameField;
        
        private string patientIdField;
        
        private string accessionIdField;
        
        private string clientIdField;
        
        private string requisitionIdField;
        
        private System.DateTime dosField;
        
        private bool dosFieldSpecified;
        
        private decimal balanceDueAmountField;
        
        private bool balanceDueAmountFieldSpecified;
        
        private decimal patientDueAmountField;
        
        private bool patientDueAmountFieldSpecified;
        
        private string patientSSNField;
        
        private System.DateTime patientDOBField;
        
        private bool patientDOBFieldSpecified;
        
        private AddressType patientAddressField;
        
        private string accessionStatusField;
        
        private string accessionStatementStatusField;
        
        private InsuranceInfo[] insuranceInfoField;
        
        private SpecificPatientInfo clientSpecificPatientInfoField;
        
        private SpecificPatientInfo facilitySpecificPatientInfoField;
        
        private bool mspFormField;
        
        private bool mspFormFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RowId {
            get {
                return this.rowIdField;
            }
            set {
                this.rowIdField = value;
                this.RaisePropertyChanged("RowId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NameType PatientName {
            get {
                return this.patientNameField;
            }
            set {
                this.patientNameField = value;
                this.RaisePropertyChanged("PatientName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PatientId {
            get {
                return this.patientIdField;
            }
            set {
                this.patientIdField = value;
                this.RaisePropertyChanged("PatientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AccessionId {
            get {
                return this.accessionIdField;
            }
            set {
                this.accessionIdField = value;
                this.RaisePropertyChanged("AccessionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RequisitionId {
            get {
                return this.requisitionIdField;
            }
            set {
                this.requisitionIdField = value;
                this.RaisePropertyChanged("RequisitionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime Dos {
            get {
                return this.dosField;
            }
            set {
                this.dosField = value;
                this.RaisePropertyChanged("Dos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DosSpecified {
            get {
                return this.dosFieldSpecified;
            }
            set {
                this.dosFieldSpecified = value;
                this.RaisePropertyChanged("DosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal BalanceDueAmount {
            get {
                return this.balanceDueAmountField;
            }
            set {
                this.balanceDueAmountField = value;
                this.RaisePropertyChanged("BalanceDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceDueAmountSpecified {
            get {
                return this.balanceDueAmountFieldSpecified;
            }
            set {
                this.balanceDueAmountFieldSpecified = value;
                this.RaisePropertyChanged("BalanceDueAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal PatientDueAmount {
            get {
                return this.patientDueAmountField;
            }
            set {
                this.patientDueAmountField = value;
                this.RaisePropertyChanged("PatientDueAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientDueAmountSpecified {
            get {
                return this.patientDueAmountFieldSpecified;
            }
            set {
                this.patientDueAmountFieldSpecified = value;
                this.RaisePropertyChanged("PatientDueAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=9)]
        public string PatientSSN {
            get {
                return this.patientSSNField;
            }
            set {
                this.patientSSNField = value;
                this.RaisePropertyChanged("PatientSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime PatientDOB {
            get {
                return this.patientDOBField;
            }
            set {
                this.patientDOBField = value;
                this.RaisePropertyChanged("PatientDOB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientDOBSpecified {
            get {
                return this.patientDOBFieldSpecified;
            }
            set {
                this.patientDOBFieldSpecified = value;
                this.RaisePropertyChanged("PatientDOBSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public AddressType PatientAddress {
            get {
                return this.patientAddressField;
            }
            set {
                this.patientAddressField = value;
                this.RaisePropertyChanged("PatientAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AccessionStatus {
            get {
                return this.accessionStatusField;
            }
            set {
                this.accessionStatusField = value;
                this.RaisePropertyChanged("AccessionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AccessionStatementStatus {
            get {
                return this.accessionStatementStatusField;
            }
            set {
                this.accessionStatementStatusField = value;
                this.RaisePropertyChanged("AccessionStatementStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InsuranceInfo", Order=14)]
        public InsuranceInfo[] InsuranceInfo {
            get {
                return this.insuranceInfoField;
            }
            set {
                this.insuranceInfoField = value;
                this.RaisePropertyChanged("InsuranceInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public SpecificPatientInfo ClientSpecificPatientInfo {
            get {
                return this.clientSpecificPatientInfoField;
            }
            set {
                this.clientSpecificPatientInfoField = value;
                this.RaisePropertyChanged("ClientSpecificPatientInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public SpecificPatientInfo FacilitySpecificPatientInfo {
            get {
                return this.facilitySpecificPatientInfoField;
            }
            set {
                this.facilitySpecificPatientInfoField = value;
                this.RaisePropertyChanged("FacilitySpecificPatientInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool MspForm {
            get {
                return this.mspFormField;
            }
            set {
                this.mspFormField = value;
                this.RaisePropertyChanged("MspForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MspFormSpecified {
            get {
                return this.mspFormFieldSpecified;
            }
            set {
                this.mspFormFieldSpecified = value;
                this.RaisePropertyChanged("MspFormSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.xifin.com/schema/accessionSearch")]
    public partial class InsuranceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string payorNameField;
        
        private string subscriberIdField;
        
        private NameType insuredNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PayorName {
            get {
                return this.payorNameField;
            }
            set {
                this.payorNameField = value;
                this.RaisePropertyChanged("PayorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubscriberId {
            get {
                return this.subscriberIdField;
            }
            set {
                this.subscriberIdField = value;
                this.RaisePropertyChanged("SubscriberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public NameType InsuredName {
            get {
                return this.insuredNameField;
            }
            set {
                this.insuredNameField = value;
                this.RaisePropertyChanged("InsuredName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccessionSearchRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.xifin.com/schema/accessionSearch", Order=0)]
        public SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest AccessionSearchRequest;
        
        public AccessionSearchRequest1() {
        }
        
        public AccessionSearchRequest1(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest AccessionSearchRequest) {
            this.AccessionSearchRequest = AccessionSearchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccessionSearchResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.xifin.com/schema/accessionSearch", Order=0)]
        public SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse AccessionSearchResponse;
        
        public AccessionSearchResponse1() {
        }
        
        public AccessionSearchResponse1(SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse AccessionSearchResponse) {
            this.AccessionSearchResponse = AccessionSearchResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface accessionSearchChannel : SignalAPILib.XifinAccessionSearchService.accessionSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class accessionSearchClient : System.ServiceModel.ClientBase<SignalAPILib.XifinAccessionSearchService.accessionSearch>, SignalAPILib.XifinAccessionSearchService.accessionSearch {
        
        public accessionSearchClient() {
        }
        
        public accessionSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public accessionSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public accessionSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public accessionSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1 SignalAPILib.XifinAccessionSearchService.accessionSearch.AccessionSearch(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 request) {
            return base.Channel.AccessionSearch(request);
        }
        
        public SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse AccessionSearch(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest AccessionSearchRequest) {
            SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 inValue = new SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1();
            inValue.AccessionSearchRequest = AccessionSearchRequest;
            SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1 retVal = ((SignalAPILib.XifinAccessionSearchService.accessionSearch)(this)).AccessionSearch(inValue);
            return retVal.AccessionSearchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1> SignalAPILib.XifinAccessionSearchService.accessionSearch.AccessionSearchAsync(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 request) {
            return base.Channel.AccessionSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<SignalAPILib.XifinAccessionSearchService.AccessionSearchResponse1> AccessionSearchAsync(SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest AccessionSearchRequest) {
            SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1 inValue = new SignalAPILib.XifinAccessionSearchService.AccessionSearchRequest1();
            inValue.AccessionSearchRequest = AccessionSearchRequest;
            return ((SignalAPILib.XifinAccessionSearchService.accessionSearch)(this)).AccessionSearchAsync(inValue);
        }
    }
}
